name: Issue Labeller
on:
  issues:
    types:
      - opened
      - edited
      - reopened
jobs:
  assign-priority-label:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: extract-priority
        uses: actions-ecosystem/action-regex-match@v2
        id: extract-priority
        with:
          text: "${{ github.event.issue.body }}"
          regex: 'A: ([^\n]+)'
          flags: "gm"
      - run: echo "${{ toJSON(steps.extract-priority.outputs) }}"
      - name: label-issue
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: ${{ steps.extract-priority.outputs.group1 == 'Yes' && 'critical' || 'ignored' }}
          repo-token: ${{ secrets.ACTIONS }}
